import { createSupabaseServerClient } from "./server.js";

/**
 * Astro middleware that populates `Astro.locals.supabase` and `Astro.locals.user`.
 *
 * Does NOT redirect — protection is explicit via `requireAuth()` per page/endpoint.
 *
 * @example
 * // src/middleware.ts (generated by CLI)
 * export { onRequest } from "astro-auth-integration/middleware";
 */
export async function onRequest(
  context: {
    request: Request;
    cookies: import("astro").AstroCookies;
    locals: App.Locals;
  },
  next: () => Promise<Response>,
) {
  const supabase = createSupabaseServerClient({
    request: context.request,
    cookies: context.cookies,
  });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  context.locals.supabase = supabase;
  context.locals.user = user;

  return next();
}
